name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y cmake

    - name: Create Build Directory
      run: mkdir build

    - name: Navigate to Build Directory
      run: cd build

    - name: Run CMake
      run: cmake ../

    - name: Build with Make
      run: make
    
    